/**
 * Utilitários para download de templates oficiais e simulação de importação em lote
 */

export const RULES_TEMPLATES = {
  SETUP: {
    filename: 'template_carga_oficial_setup_acerto_ciafal.csv',
    headers: [
      'Centro',
      'Linha',
      'Centro_Trabalho',
      'Familia_DE',
      'Codigo_DE',
      'Descricao_DE',
      'Familia_PARA',
      'Codigo_PARA',
      'Descricao_PARA',
      'Tempo_Setup_Min',
      'Tempo_Acerto_Min',
      'Origem',
      'Vigencia_Inicio',
      'Responsavel',
    ],
    sampleRows: [
      [
        '1001',
        'L1',
        'WC-DIV-L1',
        'TUB_QUAD',
        'TQ-20x20',
        'Tubo Quadrado 20x20',
        'TUB_RET',
        'TR-80x40',
        'Tubo Retangular 80x40',
        '90',
        '25',
        'SAP',
        '2026-01-01',
        'Engenharia de Processos',
      ],
      [
        '1001',
        'L1',
        'WC-DIV-L1',
        '*',
        '*',
        'Regra Genérica de Entrada',
        'TUB_RED',
        'TR-OD-50',
        'Tubo Redondo 50mm',
        '110',
        '30',
        'MANUAL',
        '2026-01-01',
        'PCP Hub',
      ],
      [
        '1002',
        'L2',
        'WC-CTG-L2',
        'PERF_U',
        'PU-150x50',
        'Perfil U Enrijecido',
        'TUB_QUAD',
        'TQ-100x100',
        'Tubo Pesado 100x100',
        '120',
        '30',
        'MANUAL',
        '2026-01-01',
        'Engenharia Contagem',
      ],
    ],
  },
  STOPS: {
    filename: 'template_carga_oficial_paradas_programadas_ciafal.csv',
    headers: [
      'Centro',
      'Linha',
      'Centro_Trabalho',
      'Tipo_Parada',
      'Motivo_Codigo',
      'Descricao',
      'Duracao_Min',
      'Hora_Inicio',
      'Recorrencia',
      'Turno',
      'Impacto_Estimado',
      'Responsavel',
    ],
    sampleRows: [
      [
        '1001',
        'L1',
        'WC-DIV-L1',
        'Manutenção Preventiva',
        'PREV_L1_SEM',
        'Manutenção Semanal e Troca de Rolos',
        '180',
        '06:00',
        'Semanal',
        'T1_L1',
        'Parada total da linha',
        'Manutenção Mecânica',
      ],
      [
        '1001',
        'L1',
        'WC-DIV-L1',
        'Limpeza Operacional',
        'LIMP_AUT_L1',
        'Limpeza e desobstrução de calhas',
        '20',
        '05:40',
        'Por Turno',
        'Todos os Turnos',
        'Descarte de cavacos',
        'Operação L1',
      ],
      [
        '1002',
        'L2',
        'WC-CTG-L2',
        'Calibração / Aferição',
        'CALIB_OPT_L2',
        'Aferição de Laser Dimensional',
        '90',
        '12:00',
        'Semanal',
        'T2_L2',
        'Checagem de tolerâncias',
        'Qualidade Industrial',
      ],
    ],
  },
  COOLING: {
    filename: 'template_carga_oficial_tempos_resfriamento_ciafal.csv',
    headers: [
      'Centro',
      'Linha_Origem',
      'Centro_Trabalho_Origem',
      'Linha_Destino',
      'Centro_Trabalho_Destino',
      'Familia',
      'Material_Bitola',
      'Tempo_Minimo_Horas',
      'Unidade',
      'Condicao_Regra',
      'Responsavel',
    ],
    sampleRows: [
      [
        '1001',
        'L1',
        'WC-DIV-L1',
        'ENDIR',
        'WC-CTG-ENDIR',
        'TUB_QUAD',
        'TQ-100x100 mm',
        '24',
        'h',
        'Cura térmica obrigatória antes de endireitamento',
        'Metalurgia CIAFAL',
      ],
      [
        '1001',
        'L1',
        'WC-DIV-L1',
        'ACAB_L2',
        'WC-CTG-ACAB_L2',
        'TUB_RET',
        'TR-80x40x2.5 mm',
        '23',
        'h',
        'Norma técnica CIAFAL N-203',
        'Metalurgia CIAFAL',
      ],
      [
        '1002',
        'L2',
        'WC-CTG-L2',
        'ENDIR',
        'WC-CTG-ENDIR',
        'PERF_U',
        'PU-150x50x4.75 mm',
        '36',
        'h',
        'Resfriamento estendido em leito ventilado',
        'Processos Contagem',
      ],
      [
        '1001',
        'ENF_L1',
        'WC-DIV-ENF_L1',
        'L1',
        'WC-DIV-L1',
        'TAR_130',
        'TAR-130-1020 (130x130mm)',
        '18',
        'h',
        'Homogeneização pós-enfornamento',
        'Aciaria & Laminação',
      ],
    ],
  },
  SEQUENCING: {
    filename: 'template_carga_oficial_regras_sequenciamento_ciafal.csv',
    headers: [
      'Linha',
      'Familia_DE',
      'Material_DE',
      'Familia_PARA',
      'Material_PARA',
      'Tipo_Regra',
      'Penalidade_Score',
      'Motivo',
      'Escopo',
    ],
    sampleRows: [
      [
        'L1',
        'TUB_RED',
        'TR-OD-50',
        'TUB_QUAD',
        'TQ-50x50',
        'PROIBITIVA',
        '100',
        'Dano mecânico em cassetes de conformação',
        'Linha',
      ],
      [
        'L2',
        'PERF_U',
        'PU-150x50',
        'PERF_U',
        'PU-100x40',
        'NAO_RECOMENDADA',
        '35',
        'Aumento de tempo de setup e risco de empenamento',
        'Linha',
      ],
      [
        'L1',
        'TUB_QUAD',
        'TQ-20x20',
        'TUB_QUAD',
        'TQ-50x50',
        'PREFERENCIAL',
        '-15',
        'Minimiza desgaste e tempo de ajuste micrométrico',
        'Global',
      ],
      [
        'L1',
        'TUB_QUAD',
        'TQ-50x50',
        'TUB_QUAD',
        'TQ-50x50',
        'NEUTRA',
        '0',
        'Mesma bitola e ferramental em lote contínuo',
        'Linha',
      ],
    ],
  },
}

export function downloadOfficialTemplate(type: keyof typeof RULES_TEMPLATES) {
  const template = RULES_TEMPLATES[type]
  if (!template) return

  const csvContent = [
    template.headers.join(';'),
    ...template.sampleRows.map((row) => row.join(';')),
  ].join('\n')

  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.setAttribute('href', url)
  link.setAttribute('download', template.filename)
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
