migrate(
  (app) => {
    const familiesCol = app.findCollectionByNameOrId('pcp_reason_families')
    const reasonsCol = app.findCollectionByNameOrId('pcp_change_reasons')
    const clustersCol = app.findCollectionByNameOrId('pcp_reason_clusters')

    // Famílias oficiais de Motivos
    const initialFamilies = [
      {
        code: 'MP',
        name: 'Matéria-prima',
        description: 'Causas ligadas a suprimento, estoque, divergência ou saldo de MP',
        color: '#059669',
        icon_name: 'Boxes',
        sort_order: 1,
      },
      {
        code: 'PRD',
        name: 'Produção',
        description: 'Causas operacionais, produtividade, ritmo de linha e restrições de fábrica',
        color: '#004C97',
        icon_name: 'Factory',
        sort_order: 2,
      },
      {
        code: 'CAP',
        name: 'Capacidade',
        description: 'Sobrecarga, gargalos estruturais e balanceamento entre postos',
        color: '#2563EB',
        icon_name: 'BarChart3',
        sort_order: 3,
      },
      {
        code: 'SET',
        name: 'Setup',
        description: 'Alterações de ferramental, trocas dimensionais e transições SMED',
        color: '#D97706',
        icon_name: 'Sliders',
        sort_order: 4,
      },
      {
        code: 'CIL',
        name: 'Oficina de Cilindros',
        description: 'Montagem, calibração, retífica e disponibilidade de cilindros de laminação',
        color: '#EA580C',
        icon_name: 'Wrench',
        sort_order: 5,
      },
      {
        code: 'MNT',
        name: 'Manutenção',
        description: 'Intervenções preventivas, corretivas e falhas em ativos industriais',
        color: '#DC2626',
        icon_name: 'ShieldAlert',
        sort_order: 6,
      },
      {
        code: 'QLD',
        name: 'Qualidade',
        description: 'Inspeções, testes laboratoriais, bloqueios SGQ e não-conformidades',
        color: '#7C3AED',
        icon_name: 'Microscope',
        sort_order: 7,
      },
      {
        code: 'COM',
        name: 'Comercial / Cliente',
        description: 'Solicitações de antecipação, postergação, alteração de volume ou prioridade',
        color: '#4F46E5',
        icon_name: 'Briefcase',
        sort_order: 8,
      },
      {
        code: 'LOG',
        name: 'Logística',
        description: 'Restrições TMS, formação de carga, veículos e expedição',
        color: '#0891B2',
        icon_name: 'Truck',
        sort_order: 9,
      },
      {
        code: 'DAD',
        name: 'Dados / Integração',
        description: 'Falhas de sincronização SAP, divergência WMS/MES ou correção cadastral',
        color: '#475569',
        icon_name: 'Network',
        sort_order: 10,
      },
      {
        code: 'PLN',
        name: 'Planejamento',
        description:
          'Otimização de grade, balanceamento de linhas e recomendações determinísticas IA',
        color: '#0284C7',
        icon_name: 'CalendarRange',
        sort_order: 11,
      },
      {
        code: 'TST',
        name: 'Teste Industrial',
        description: 'Desenvolvimento de novos produtos, ensaios piloto e processos experimentais',
        color: '#9333EA',
        icon_name: 'FlaskConical',
        sort_order: 12,
      },
      {
        code: 'OUT',
        name: 'Outros',
        description: 'Causas excepcionais não mapeadas nas taxonomias padronizadas',
        color: '#64748B',
        icon_name: 'HelpCircle',
        sort_order: 13,
      },
    ]

    const familyRecordMap = {}

    for (const fam of initialFamilies) {
      try {
        const existing = app.findFirstRecordByData('pcp_reason_families', 'code', fam.code)
        familyRecordMap[fam.code] = existing
      } catch (_) {
        const rec = new Record(familiesCol)
        rec.set('code', fam.code)
        rec.set('name', fam.name)
        rec.set('description', fam.description)
        rec.set('color', fam.color)
        rec.set('icon_name', fam.icon_name)
        rec.set('sort_order', fam.sort_order)
        rec.set('active', true)
        app.save(rec)
        familyRecordMap[fam.code] = rec
      }
    }

    // Motivos Padrão Oficiais
    const initialReasons = [
      // Matéria-prima
      {
        code: 'MP-001',
        fam: 'MP',
        name: 'Saldo insuficiente de MP',
        desc: 'Volume físico de matéria-prima no depósito inferior à necessidade da ordem.',
        sev: 'ALTA',
        src: 'SAP MM / WMS',
        mod: 'SAP,WMS,MES',
        d: true,
        s: true,
        q: true,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: true,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: true,
      },
      {
        code: 'MP-002',
        fam: 'MP',
        name: 'MP indisponível no pátio',
        desc: 'Material cadastrado em estoque porém não localizado fisicamente no pátio.',
        sev: 'ALTA',
        src: 'WMS / Pátio de Tarugos',
        mod: 'WMS,SAP',
        d: true,
        s: true,
        q: true,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: true,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: true,
        plano: true,
      },
      {
        code: 'MP-003',
        fam: 'MP',
        name: 'Atraso no recebimento de fornecedor',
        desc: 'Pedido de compra de tarugo com data de entrega repactuada pela aciaria.',
        sev: 'ALTA',
        src: 'SAP MM / Compras',
        mod: 'SAP,CRM',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: true,
        n_tms: true,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },
      {
        code: 'MP-004',
        fam: 'MP',
        name: 'Material bloqueado por inspeção',
        desc: 'Lote de matéria-prima sob análise química ou dimensional pelo laboratório.',
        sev: 'ALTA',
        src: 'SGQ / Qualidade MP',
        mod: 'QUALIDADE,SAP',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: true,
        plano: true,
      },
      {
        code: 'MP-005',
        fam: 'MP',
        name: 'Divergência dimensional na matéria-prima',
        desc: 'Seção, comprimento ou empenamento fora da especificação da Ficha Mestre.',
        sev: 'MEDIA',
        src: 'SGQ / Ficha Mestre',
        mod: 'QUALIDADE,FICHA_MESTRE',
        d: true,
        s: true,
        q: true,
        l: false,
        t: false,
        c: true,
        e: true,
        a: false,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: true,
        plano: false,
      },
      {
        code: 'MP-006',
        fam: 'MP',
        name: 'MP destinada a outra aplicação',
        desc: 'Reaplicação autorizada do bloco/tarugo para ordem de maior criticidade.',
        sev: 'MEDIA',
        src: 'Otimizador ZPP86',
        mod: 'SAP,MES',
        d: true,
        s: true,
        q: true,
        l: false,
        t: false,
        c: true,
        e: false,
        a: false,
        crit: 'NORMAL',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },
      {
        code: 'MP-007',
        fam: 'MP',
        name: 'MP aguardando industrializador',
        desc: 'Remessa em trânsito ou pendente de descarregamento no parceiro terceirizado.',
        sev: 'MEDIA',
        src: 'Módulo Industrializador / SAP',
        mod: 'SAP,WMS',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: false,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: true,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },

      // Produção
      {
        code: 'PRD-001',
        fam: 'PRD',
        name: 'Redução de produtividade observada',
        desc: 'Ritmo real da linha inferior à taxa nominal prevista na Ficha Mestre.',
        sev: 'MEDIA',
        src: 'MES / Telemetria',
        mod: 'MES,FICHA_MESTRE',
        d: true,
        s: false,
        q: true,
        l: false,
        t: true,
        c: true,
        e: true,
        a: false,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: true,
        n_cil: false,
        sgq: false,
        plano: true,
      },
      {
        code: 'PRD-002',
        fam: 'PRD',
        name: 'Indisponibilidade temporária da linha',
        desc: 'Parada operacional não programada durante o turno de trabalho.',
        sev: 'ALTA',
        src: 'MES / Apontamento',
        mod: 'MES',
        d: true,
        s: true,
        q: false,
        l: true,
        t: true,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: true,
        n_tms: false,
        n_pcm: true,
        n_cil: false,
        sgq: false,
        plano: true,
      },
      {
        code: 'PRD-003',
        fam: 'PRD',
        name: 'Alteração de sequência operacional',
        desc: 'Reordenamento de lotes para ganho térmico ou agrupamento de perfil.',
        sev: 'BAIXA',
        src: 'Motor de Regras PCP',
        mod: 'MOTOR_REGRAS',
        d: false,
        s: true,
        q: false,
        l: false,
        t: false,
        c: false,
        e: false,
        a: false,
        crit: 'NORMAL',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },
      {
        code: 'PRD-004',
        fam: 'PRD',
        name: 'Restrição operacional de segurança / processo',
        desc: 'Limitação imposta por condição térmica, exaustão ou segurança fabril.',
        sev: 'ALTA',
        src: 'Engenharia / Segurança',
        mod: 'MES,FICHA_MESTRE',
        d: true,
        s: true,
        q: true,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: true,
        plano: true,
      },
      {
        code: 'PRD-005',
        fam: 'PRD',
        name: 'Recuperação de produção atrasada',
        desc: 'Antecipação de lote pendente de turno anterior na janela disponível.',
        sev: 'BAIXA',
        src: 'PCP Programação',
        mod: 'MES,SAP',
        d: true,
        s: true,
        q: true,
        l: false,
        t: true,
        c: false,
        e: false,
        a: false,
        crit: 'NORMAL',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },

      // Manutenção
      {
        code: 'MNT-001',
        fam: 'MNT',
        name: 'Manutenção corretiva emergencial',
        desc: 'Quebra ou falha mecânica/elétrica súbita exigindo parada imediata.',
        sev: 'CRITICA',
        src: 'PCM / SAP PM',
        mod: 'PCM,MES',
        d: true,
        s: true,
        q: true,
        l: true,
        t: true,
        c: true,
        e: true,
        a: true,
        crit: 'BLOQUEANTE',
        n_mes: true,
        n_crm: true,
        n_tms: true,
        n_pcm: true,
        n_cil: false,
        sgq: true,
        plano: true,
      },
      {
        code: 'MNT-002',
        fam: 'MNT',
        name: 'Manutenção preventiva programada',
        desc: 'Ajuste de grade para realização de plano de manutenção preventiva.',
        sev: 'MEDIA',
        src: 'PCM / Calendário de Manutenção',
        mod: 'PCM,FICHA_MESTRE',
        d: true,
        s: true,
        q: false,
        l: false,
        t: true,
        c: true,
        e: false,
        a: false,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: true,
        n_cil: false,
        sgq: false,
        plano: false,
      },
      {
        code: 'MNT-003',
        fam: 'MNT',
        name: 'Falha de equipamento auxiliar',
        desc: 'Pane em tesoura, ponte rolante, endireitadeira ou empacotador.',
        sev: 'ALTA',
        src: 'MES / PCM',
        mod: 'PCM,MES',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: true,
        n_cil: false,
        sgq: false,
        plano: true,
      },
      {
        code: 'MNT-004',
        fam: 'MNT',
        name: 'Indisponibilidade de forno / aquecimento',
        desc: 'Falha no queimador, refratário ou controle térmico do forno de reaquecimento.',
        sev: 'CRITICA',
        src: 'MES / Telemetria Forno',
        mod: 'MES,PCM',
        d: true,
        s: true,
        q: true,
        l: false,
        t: true,
        c: true,
        e: true,
        a: true,
        crit: 'BLOQUEANTE',
        n_mes: true,
        n_crm: true,
        n_tms: true,
        n_pcm: true,
        n_cil: false,
        sgq: true,
        plano: true,
      },

      // Setup
      {
        code: 'SET-001',
        fam: 'SET',
        name: 'Alteração de matriz de setup',
        desc: 'Ajuste na sequência de passes e ferramentas para atender bitola.',
        sev: 'BAIXA',
        src: 'Motor de Setup / Regras',
        mod: 'MOTOR_REGRAS',
        d: false,
        s: true,
        q: false,
        l: false,
        t: false,
        c: false,
        e: false,
        a: false,
        crit: 'NORMAL',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: true,
        sgq: false,
        plano: false,
      },
      {
        code: 'SET-002',
        fam: 'SET',
        name: 'Setup acima do tempo previsto',
        desc: 'Tempo real de troca e regulagem superior à tabela padrão.',
        sev: 'MEDIA',
        src: 'MES / Apontamento Setup',
        mod: 'MES,FICHA_MESTRE',
        d: true,
        s: false,
        q: true,
        l: false,
        t: false,
        c: true,
        e: true,
        a: false,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: true,
        sgq: false,
        plano: true,
      },
      {
        code: 'SET-003',
        fam: 'SET',
        name: 'Necessidade de troca adicional de guias',
        desc: 'Desgaste acelerado exigindo substituição intermediária de ferramental.',
        sev: 'MEDIA',
        src: 'Chão de Fábrica / Oficina',
        mod: 'OFICINA_CILINDROS,MES',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: false,
        a: false,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: true,
        sgq: false,
        plano: false,
      },

      // Oficina de Cilindros
      {
        code: 'CIL-001',
        fam: 'CIL',
        name: 'Cilindro indisponível na retífica',
        desc: 'Par de cilindros em processo de usinagem ou aguardando liberação dimensional.',
        sev: 'ALTA',
        src: 'Oficina de Cilindros',
        mod: 'OFICINA_CILINDROS',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: true,
        sgq: false,
        plano: true,
      },
      {
        code: 'CIL-002',
        fam: 'CIL',
        name: 'Cilindro aguardando preparação e montagem',
        desc: 'Montagem de mancais, anéis e guias pendente na oficina.',
        sev: 'MEDIA',
        src: 'Oficina de Cilindros',
        mod: 'OFICINA_CILINDROS',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: false,
        a: false,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: true,
        sgq: false,
        plano: false,
      },
      {
        code: 'CIL-003',
        fam: 'CIL',
        name: 'Ferramental / guias danificadas',
        desc: 'Trinca ou dano em calibres exigindo troca imediata de conjunto.',
        sev: 'ALTA',
        src: 'Oficina de Cilindros / Inspeção',
        mod: 'OFICINA_CILINDROS,SGQ',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: true,
        sgq: true,
        plano: true,
      },

      // Qualidade
      {
        code: 'QLD-001',
        fam: 'QLD',
        name: 'Produto retido para reinspeção',
        desc: 'Lote anterior sob análise de dureza, ensaio mecânico ou ultrassom.',
        sev: 'ALTA',
        src: 'SGQ / Laboratório',
        mod: 'QUALIDADE,SAP',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: true,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: true,
        plano: true,
      },
      {
        code: 'QLD-002',
        fam: 'QLD',
        name: 'Necessidade de retrabalho de lote',
        desc: 'Reenfornamento ou reprocesso de barras fora de tolerância dimensional.',
        sev: 'ALTA',
        src: 'SGQ / Apontamento',
        mod: 'QUALIDADE,MES',
        d: true,
        s: true,
        q: true,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: true,
        plano: true,
      },
      {
        code: 'QLD-003',
        fam: 'QLD',
        name: 'Resultado de ensaio crítico pendente',
        desc: 'Laudo de qualidade indispensável para prosseguimento da campanha MTO.',
        sev: 'MEDIA',
        src: 'SGQ / Ficha de Requisitos',
        mod: 'QUALIDADE',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: false,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },

      // Comercial / Cliente
      {
        code: 'COM-001',
        fam: 'COM',
        name: 'Antecipação solicitada pelo cliente',
        desc: 'Demanda comercial com adiantamento acordado via CRM.',
        sev: 'MEDIA',
        src: 'CRM 360º / Vendas',
        mod: 'CRM,TMS',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: true,
        n_tms: true,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },
      {
        code: 'COM-002',
        fam: 'COM',
        name: 'Postergação solicitada pelo cliente',
        desc: 'Cliente sem espaço em pátio solicitando postergar janela de entrega.',
        sev: 'MEDIA',
        src: 'CRM 360º / Vendas',
        mod: 'CRM,TMS',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: false,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: true,
        n_tms: true,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },
      {
        code: 'COM-003',
        fam: 'COM',
        name: 'Alteração de quantidade do pedido',
        desc: 'Ajuste no volume faturável da ordem de venda SAP.',
        sev: 'MEDIA',
        src: 'SAP SD / Carteira ZSD28C',
        mod: 'SAP,CRM',
        d: false,
        s: false,
        q: true,
        l: false,
        t: false,
        c: true,
        e: true,
        a: false,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: true,
        n_tms: true,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },
      {
        code: 'COM-004',
        fam: 'COM',
        name: 'Pedido prioritário estratégico',
        desc: 'Inclusão de lote por diretriz executiva ou contrato especial.',
        sev: 'ALTA',
        src: 'Diretoria Comercial / CRM',
        mod: 'CRM,SAP',
        d: true,
        s: true,
        q: true,
        l: false,
        t: true,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: true,
        n_tms: true,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },

      // Logística
      {
        code: 'LOG-001',
        fam: 'LOG',
        name: 'Restrição de formação de carga TMS',
        desc: 'Necessidade de consolidação de peso/volume para viabilizar frete.',
        sev: 'MEDIA',
        src: 'TMS Logística',
        mod: 'TMS,CRM',
        d: true,
        s: true,
        q: true,
        l: false,
        t: false,
        c: true,
        e: true,
        a: false,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: true,
        n_tms: true,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },
      {
        code: 'LOG-002',
        fam: 'LOG',
        name: 'Pátio de expedição com lotação máxima',
        desc: 'Estoque de produto acabado aguardando transporte impedindo novos pacotes.',
        sev: 'ALTA',
        src: 'WMS / Logística de Pátio',
        mod: 'WMS,TMS',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'CRITICA',
        n_mes: true,
        n_crm: false,
        n_tms: true,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: true,
      },

      // Dados / Integração
      {
        code: 'DAD-001',
        fam: 'DAD',
        name: 'Correção de dados mestres SAP',
        desc: 'Ajuste cadastral de roteiro, centro de trabalho ou peso teórico.',
        sev: 'BAIXA',
        src: 'SAP ECC / Engenharia',
        mod: 'SAP,FICHA_MESTRE',
        d: false,
        s: false,
        q: true,
        l: false,
        t: false,
        c: true,
        e: false,
        a: false,
        crit: 'NORMAL',
        n_mes: false,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },
      {
        code: 'DAD-002',
        fam: 'DAD',
        name: 'Falha temporária de interface / conector',
        desc: 'Fila de sincronização RFC ou OData degradada durante a publicação.',
        sev: 'MEDIA',
        src: 'Monitor de Integrações',
        mod: 'SAP,MES',
        d: false,
        s: false,
        q: false,
        l: false,
        t: false,
        c: true,
        e: true,
        a: false,
        crit: 'ATENCAO',
        n_mes: false,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },

      // Planejamento
      {
        code: 'PLN-001',
        fam: 'PLN',
        name: 'Otimização de sequência e campanha',
        desc: 'Reagrupamento determinístico para minimizar trocas e consumo térmico.',
        sev: 'BAIXA',
        src: 'Motor IA CIAFAL',
        mod: 'MOTOR_REGRAS',
        d: true,
        s: true,
        q: false,
        l: false,
        t: false,
        c: false,
        e: false,
        a: false,
        crit: 'NORMAL',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },
      {
        code: 'PLN-002',
        fam: 'PLN',
        name: 'Balanceamento de capacidade entre linhas',
        desc: 'Transferência de perfil compatível para linha alternativa desobstruída.',
        sev: 'MEDIA',
        src: 'Torre de Controle PCP',
        mod: 'FICHA_MESTRE,MATRIZ_GARGALO',
        d: true,
        s: true,
        q: true,
        l: true,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: false,
        sgq: false,
        plano: false,
      },

      // Teste
      {
        code: 'TST-001',
        fam: 'TST',
        name: 'Teste industrial de novo produto',
        desc: 'Janela reservada para corrida experimental acompanhada pela Engenharia.',
        sev: 'MEDIA',
        src: 'Engenharia de Processo',
        mod: 'FICHA_MESTRE,QUALIDADE',
        d: true,
        s: true,
        q: true,
        l: false,
        t: false,
        c: true,
        e: true,
        a: true,
        crit: 'ATENCAO',
        n_mes: true,
        n_crm: false,
        n_tms: false,
        n_pcm: false,
        n_cil: true,
        sgq: true,
        plano: false,
      },
    ]

    for (const r of initialReasons) {
      try {
        app.findFirstRecordByData('pcp_change_reasons', 'code', r.code)
      } catch (_) {
        const rec = new Record(reasonsCol)
        const famRec = familyRecordMap[r.fam]
        rec.set('code', r.code)
        if (famRec) {
          rec.set('family_id', famRec.id)
          rec.set('family_code', famRec.get('code'))
          rec.set('family_name', famRec.get('name'))
        }
        rec.set('name', r.name)
        rec.set('description', r.desc)
        rec.set('severity', r.sev)
        rec.set('source_type', r.src)
        rec.set('related_modules', r.mod)
        rec.set('allows_date_change', r.d)
        rec.set('allows_sequence_change', r.s)
        rec.set('allows_quantity_change', r.q)
        rec.set('allows_line_change', r.l)
        rec.set('allows_shift_change', r.t)
        rec.set('require_comment', r.c)
        rec.set('require_evidence', r.e)
        rec.set('require_approval', r.a)
        rec.set('criticality', r.crit)
        rec.set('notify_mes', r.n_mes)
        rec.set('notify_crm', r.n_crm)
        rec.set('notify_tms', r.n_tms)
        rec.set('notify_pcm', r.n_pcm)
        rec.set('notify_roll_shop', r.n_cil)
        rec.set('generate_sgq_occurrence', r.sgq)
        rec.set('generate_action_plan', r.plano)
        rec.set('count_as_reprogram_cause', true)
        rec.set('created_by_name', 'CIAFAL Sistema Mestre')
        rec.set('updated_by_name', 'CIAFAL Sistema Mestre')
        rec.set('active', true)
        app.save(rec)
      }
    }

    // Sugestões de agrupamento / Clusters IA iniciais (Aba 2)
    const initialClusters = [
      {
        code: 'CLUST-001',
        name: 'Cilindro indisponível para setup de cantoneira',
        p_code: 'SET-004',
        f_code: 'CIL',
        f_name: 'Oficina de Cilindros',
        count: 17,
        sim: 96.4,
        hrs: 38.4,
        tons: 420.0,
        terms: ['cilindro', 'desgaste', 'retífica', 'cantoneira', 'montagem de calibres'],
        samples: [
          'Cilindro não retornou a tempo da oficina para troca da Linha 1.',
          'Atraso na montagem de mancais do calibre 2 polegadas na oficina de cilindros.',
          'Retífica de cilindros com fila de espera para laminador contínuo.',
        ],
        lines: ['L1', 'L2'],
        status: 'PROPOSED',
        notes:
          'Identificado pela IA através da correlação semântica de 17 justificativas textuais livres.',
      },
      {
        code: 'CLUST-002',
        name: 'Atraso no descarregamento de tarugos especiais',
        p_code: 'MP-008',
        f_code: 'MP',
        f_name: 'Matéria-prima',
        count: 9,
        sim: 92.1,
        hrs: 21.6,
        tons: 280.0,
        terms: [
          'fila de caminhão',
          'ponte rolante',
          'recebimento',
          'pátio saturado',
          'tarugo especial',
        ],
        samples: [
          'Caminhão da aciaria aguardando descarregamento no pátio KS.',
          'Ponte rolante ocupada com alimentação do forno impedindo descarregamento de MP.',
        ],
        lines: ['L1'],
        status: 'PROPOSED',
        notes: 'Alta frequência em turnos matutinos de segunda e terça-feira.',
      },
    ]

    for (const c of initialClusters) {
      try {
        app.findFirstRecordByData('pcp_reason_clusters', 'cluster_code', c.code)
      } catch (_) {
        const rec = new Record(clustersCol)
        rec.set('cluster_code', c.code)
        rec.set('proposed_name', c.name)
        rec.set('proposed_code', c.p_code)
        rec.set('proposed_family_code', c.f_code)
        rec.set('proposed_family_name', c.f_name)
        rec.set('occurrence_count', c.count)
        rec.set('similarity_score', c.sim)
        rec.set('impact_hours', c.hrs)
        rec.set('impact_tons', c.tons)
        rec.set('recurring_terms', c.terms)
        rec.set('sample_justifications', c.samples)
        rec.set('affected_lines', c.lines)
        rec.set('status', c.status)
        rec.set('notes', c.notes)
        app.save(rec)
      }
    }
  },
  (app) => {
    // rollback se necessário
  },
)
