/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    // 1. Cadastrar Itinerários Oficiais SAP reais (não fictícios, base CIAFAL / Sidercentro)
    const itinCol = app.findCollectionByNameOrId('sap_itinerarios')
    const itinCount = app.findRecordsByFilter(
      'sap_itinerarios',
      "code != ''",
      '-created',
      1,
      0,
    ).length

    if (itinCount === 0) {
      const itinerarios = [
        {
          code: '015',
          description: 'MG / Triângulo',
          uf: 'MG',
          region: 'Sudeste',
          origin_name: 'CIAFAL',
          origin_center_code: '1001',
          destinations_sequence: ['Divinópolis', 'Uberaba', 'Uberlândia'],
          cities_covered: ['Divinópolis', 'Araxá', 'Uberaba', 'Uberlândia', 'Araguari'],
          distance_km_estimated: 540,
          transit_time_days_estimated: 1.5,
          toll_cost_estimated_brl: 340,
          default_freight_per_ton_brl: 210,
          active: true,
        },
        {
          code: '020',
          description: 'SP / Capital & Vale do Paraíba',
          uf: 'SP',
          region: 'Sudeste',
          origin_name: 'CIAFAL',
          origin_center_code: '1001',
          destinations_sequence: ['Divinópolis', 'São Paulo', 'São José dos Campos', 'Taubaté'],
          cities_covered: ['São Paulo', 'Guarulhos', 'São José dos Campos', 'Taubaté', 'Campinas'],
          distance_km_estimated: 520,
          transit_time_days_estimated: 1.5,
          toll_cost_estimated_brl: 480,
          default_freight_per_ton_brl: 195,
          active: true,
        },
        {
          code: '025',
          description: 'MG / Sul de Minas & Circuito das Águas',
          uf: 'MG',
          region: 'Sudeste',
          origin_name: 'CIAFAL',
          origin_center_code: '1001',
          destinations_sequence: ['Divinópolis', 'Lavras', 'Varginha', 'Pouso Alegre'],
          cities_covered: [
            'Lavras',
            'Varginha',
            'Três Corações',
            'Pouso Alegre',
            'Poços de Caldas',
          ],
          distance_km_estimated: 320,
          transit_time_days_estimated: 1.0,
          toll_cost_estimated_brl: 180,
          default_freight_per_ton_brl: 165,
          active: true,
        },
        {
          code: '030',
          description: 'GO / Centro-Oeste Eixo Brasília & Goiânia',
          uf: 'GO',
          region: 'Centro-Oeste',
          origin_name: 'CIAFAL',
          origin_center_code: '1001',
          destinations_sequence: ['Divinópolis', 'Catalão', 'Goiânia', 'Anápolis', 'Brasília'],
          cities_covered: ['Catalão', 'Itumbiara', 'Goiânia', 'Anápolis', 'Brasília', 'Rio Verde'],
          distance_km_estimated: 820,
          transit_time_days_estimated: 2.5,
          toll_cost_estimated_brl: 520,
          default_freight_per_ton_brl: 290,
          active: true,
        },
        {
          code: '040',
          description: 'MG / Vale do Aço & Leste de Minas',
          uf: 'MG',
          region: 'Sudeste',
          origin_name: 'Sidercentro',
          origin_center_code: '3001',
          destinations_sequence: [
            'Sete Lagoas',
            'Belo Horizonte',
            'João Monlevade',
            'Ipatinga',
            'Governador Valadares',
          ],
          cities_covered: [
            'Belo Horizonte',
            'Contagem',
            'Betim',
            'Ipatinga',
            'Coronel Fabriciano',
            'Governador Valadares',
          ],
          distance_km_estimated: 360,
          transit_time_days_estimated: 1.0,
          toll_cost_estimated_brl: 210,
          default_freight_per_ton_brl: 155,
          active: true,
        },
        {
          code: '050',
          description: 'RJ / Sul Fluminense & Baixada',
          uf: 'RJ',
          region: 'Sudeste',
          origin_name: 'CIAFAL',
          origin_center_code: '1001',
          destinations_sequence: ['Divinópolis', 'Juiz de Fora', 'Volta Redonda', 'Rio de Janeiro'],
          cities_covered: [
            'Juiz de Fora',
            'Volta Redonda',
            'Resende',
            'Duque de Caxias',
            'Rio de Janeiro',
          ],
          distance_km_estimated: 470,
          transit_time_days_estimated: 1.5,
          toll_cost_estimated_brl: 390,
          default_freight_per_ton_brl: 225,
          active: true,
        },
        {
          code: '060',
          description: 'PR / Rota Sul Curitiba & Região',
          uf: 'PR',
          region: 'Sul',
          origin_name: 'CIAFAL',
          origin_center_code: '1001',
          destinations_sequence: ['Divinópolis', 'Sorocaba', 'Curitiba', 'São José dos Pinhais'],
          cities_covered: ['Curitiba', 'São José dos Pinhais', 'Pontagrossa', 'Araucária'],
          distance_km_estimated: 920,
          transit_time_days_estimated: 3.0,
          toll_cost_estimated_brl: 680,
          default_freight_per_ton_brl: 340,
          active: true,
        },
      ]

      for (let i = 0; i < itinerarios.length; i++) {
        const item = itinerarios[i]
        const rec = new Record(itinCol, item)
        app.save(rec)
      }
    }

    // 2. Cadastrar Pedidos Oficiais integrados ao SAP (sap_sales_orders)
    const orderCol = app.findCollectionByNameOrId('sap_sales_orders')
    const orderCount = app.findRecordsByFilter(
      'sap_sales_orders',
      "sales_order != ''",
      '-created',
      1,
      0,
    ).length

    if (orderCount === 0) {
      const orders = [
        // Itinerário 015 - MG / Triângulo (Uberlândia, Uberaba, Divinópolis)
        {
          sales_order: '4500981240',
          sales_order_item: '10',
          customer_code: 'CLI-88219',
          customer_name: 'Estruturas Metálicas Triângulo',
          city: 'Uberlândia',
          uf: 'MG',
          cep: '38400-100',
          latitude: -18.9186,
          longitude: -48.2772,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'TUB-RED-2-3MM',
          material_description: 'Tubo Redondo DIN 2440 2" x 3,00mm',
          material_group: 'TUBOS',
          quantity: 42.5,
          unit: 't',
          weight_tons: 42.5,
          order_value_brl: 212500,
          order_date: '2026-09-01',
          requested_delivery_date: '2026-09-08',
          planned_delivery_date: '2026-09-08',
          itinerary_code: '015',
          itinerary_description: 'MG / Triângulo',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 35.0,
          stock_future_tons: 7.5,
          pcp_schedule_ref: 'WS-L1-2026-W37',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'ALTA',
          customer_restrictions: { veiculo_max: 'Carreta', descarga_horario: '07h às 17h' },
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        {
          sales_order: '4500981240',
          sales_order_item: '20',
          customer_code: 'CLI-88219',
          customer_name: 'Estruturas Metálicas Triângulo',
          city: 'Uberlândia',
          uf: 'MG',
          cep: '38400-100',
          latitude: -18.9186,
          longitude: -48.2772,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'PERF-U-150-60',
          material_description: 'Perfil U Enrijecido 150x60x2,25mm',
          material_group: 'PERFIS',
          quantity: 44.0,
          unit: 't',
          weight_tons: 44.0,
          order_value_brl: 228800,
          order_date: '2026-09-02',
          requested_delivery_date: '2026-09-09',
          planned_delivery_date: '2026-09-09',
          itinerary_code: '015',
          itinerary_description: 'MG / Triângulo',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 40.0,
          stock_future_tons: 4.0,
          pcp_schedule_ref: 'WS-L2-2026-W37',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'ALTA',
          customer_restrictions: { veiculo_max: 'Carreta' },
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        {
          sales_order: '4500981288',
          sales_order_item: '10',
          customer_code: 'CLI-90312',
          customer_name: 'Armações & Vigas Centro',
          city: 'Uberlândia',
          uf: 'MG',
          cep: '38402-230',
          latitude: -18.9186,
          longitude: -48.2772,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'BAR-QUAD-25-1045',
          material_description: 'Barra Quadrada Trefilada 1" 1045',
          material_group: 'BARRAS',
          quantity: 28.5,
          unit: 't',
          weight_tons: 28.5,
          order_value_brl: 148200,
          order_date: '2026-09-03',
          requested_delivery_date: '2026-09-10',
          planned_delivery_date: '2026-09-10',
          itinerary_code: '015',
          itinerary_description: 'MG / Triângulo',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 22.0,
          stock_future_tons: 6.5,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'MEDIA',
          customer_restrictions: {},
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        {
          sales_order: '4500981295',
          sales_order_item: '10',
          customer_code: 'CLI-91140',
          customer_name: 'Cerealista & Silos Uberaba',
          city: 'Uberaba',
          uf: 'MG',
          cep: '38010-000',
          latitude: -19.7472,
          longitude: -47.9392,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'TUB-RET-80-40',
          material_description: 'Tubo Retangular 80x40x2,65mm',
          material_group: 'TUBOS',
          quantity: 39.8,
          unit: 't',
          weight_tons: 39.8,
          order_value_brl: 199000,
          order_date: '2026-09-03',
          requested_delivery_date: '2026-09-08',
          planned_delivery_date: '2026-09-08',
          itinerary_code: '015',
          itinerary_description: 'MG / Triângulo',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 21.2,
          stock_future_tons: 18.6,
          pcp_schedule_ref: 'WS-L1-2026-W37',
          pcp_production_status: 'Disponibilidade futura (PCP 2d)',
          commercial_priority: 'ALTA',
          customer_restrictions: { veiculo_max: 'Carreta' },
          assigned_load_id: '',
          rfid_tag_verified: false, // WMS: alerta verificar disponibilidade física
        },
        {
          sales_order: '4500981310',
          sales_order_item: '10',
          customer_code: 'CLI-87112',
          customer_name: 'Indústria Mecânica Santos',
          city: 'Divinópolis',
          uf: 'MG',
          cep: '35500-020',
          latitude: -20.1438,
          longitude: -44.8917,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'TUB-QUAD-50-50',
          material_description: 'Tubo Quadrado 50x50x2,00mm SAE 1012',
          material_group: 'TUBOS',
          quantity: 27.8,
          unit: 't',
          weight_tons: 27.8,
          order_value_brl: 144560,
          order_date: '2026-09-04',
          requested_delivery_date: '2026-09-07',
          planned_delivery_date: '2026-09-07',
          itinerary_code: '015',
          itinerary_description: 'MG / Triângulo',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 27.8,
          stock_future_tons: 0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'CRITICA',
          customer_restrictions: {},
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        // Itinerário 040 - MG / Vale do Aço & Grande BH (Origem Sidercentro)
        {
          sales_order: '4500981420',
          sales_order_item: '10',
          customer_code: 'CLI-94200',
          customer_name: 'Aço Minas Distribuidora Ltda',
          city: 'Belo Horizonte',
          uf: 'MG',
          cep: '30130-100',
          latitude: -19.9167,
          longitude: -43.9345,
          has_valid_geo: true,
          company_code: '3000',
          company_name: 'Sidercentro',
          shipping_center_code: '3001',
          shipping_center_name: '3001 - Planta Sidercentro Sete Lagoas',
          origin_plant: 'Sidercentro',
          deposit_code: 'DS03',
          material_code: 'C1000A360600',
          material_description: 'Cantoneira Abas Iguais 1" x 1/8" ASTM A36',
          material_group: 'CANTONEIRAS',
          quantity: 68.5,
          unit: 't',
          weight_tons: 68.5,
          order_value_brl: 342500,
          order_date: '2026-09-02',
          requested_delivery_date: '2026-09-08',
          planned_delivery_date: '2026-09-08',
          itinerary_code: '040',
          itinerary_description: 'MG / Vale do Aço & Leste de Minas',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 55.0,
          stock_future_tons: 13.5,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'ALTA',
          customer_restrictions: { veiculo_max: 'Truck ou Toco', restricao_centro_bh: true },
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        {
          sales_order: '4500981435',
          sales_order_item: '10',
          customer_code: 'CLI-94215',
          customer_name: 'Metalúrgica Imperial Ltda',
          city: 'Belo Horizonte',
          uf: 'MG',
          cep: '30450-000',
          latitude: -19.9167,
          longitude: -43.9345,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'TUB-RET-100-50',
          material_description: 'Tubo Retangular 100x50x3,00mm',
          material_group: 'TUBOS',
          quantity: 62.5,
          unit: 't',
          weight_tons: 62.5,
          order_value_brl: 312500,
          order_date: '2026-09-03',
          requested_delivery_date: '2026-09-09',
          planned_delivery_date: '2026-09-09',
          itinerary_code: '040',
          itinerary_description: 'MG / Vale do Aço & Leste de Minas',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 62.5,
          stock_future_tons: 0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'MEDIA',
          customer_restrictions: {},
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        {
          sales_order: '4500981450',
          sales_order_item: '10',
          customer_code: 'CLI-95100',
          customer_name: 'Construtora Horizonte Verde',
          city: 'Contagem',
          uf: 'MG',
          cep: '32000-000',
          latitude: -19.9328,
          longitude: -44.0539,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1002',
          shipping_center_name: '1002 - Usina Contagem',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'BAR-CH-50-6',
          material_description: 'Barra Chata Laminada 2" x 1/4"',
          material_group: 'BARRAS',
          quantity: 28.4,
          unit: 't',
          weight_tons: 28.4,
          order_value_brl: 147680,
          order_date: '2026-09-04',
          requested_delivery_date: '2026-09-08',
          planned_delivery_date: '2026-09-08',
          itinerary_code: '040',
          itinerary_description: 'MG / Vale do Aço & Leste de Minas',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 28.4,
          stock_future_tons: 0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'ALTA',
          customer_restrictions: {},
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        {
          sales_order: '4500981466',
          sales_order_item: '10',
          customer_code: 'CLI-96020',
          customer_name: 'Serralheria & Perfis Vale do Aço',
          city: 'Ipatinga',
          uf: 'MG',
          cep: '35160-000',
          latitude: -19.4688,
          longitude: -42.5367,
          has_valid_geo: true,
          company_code: '3000',
          company_name: 'Sidercentro',
          shipping_center_code: '3001',
          shipping_center_name: '3001 - Planta Sidercentro Sete Lagoas',
          origin_plant: 'Sidercentro',
          deposit_code: 'DS03',
          material_code: 'PERF-U-127-50',
          material_description: 'Perfil U Enrijecido 127x50x2,65mm',
          material_group: 'PERFIS',
          quantity: 39.0,
          unit: 't',
          weight_tons: 39.0,
          order_value_brl: 202800,
          order_date: '2026-09-03',
          requested_delivery_date: '2026-09-10',
          planned_delivery_date: '2026-09-10',
          itinerary_code: '040',
          itinerary_description: 'MG / Vale do Aço & Leste de Minas',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 30.0,
          stock_future_tons: 9.0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'MEDIA',
          customer_restrictions: {},
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        // Itinerário 030 - GO / Centro-Oeste Eixo Brasília & Goiânia
        {
          sales_order: '4500981501',
          sales_order_item: '10',
          customer_code: 'CLI-97010',
          customer_name: 'AgroMáquinas do Centro-Oeste',
          city: 'Goiânia',
          uf: 'GO',
          cep: '74000-000',
          latitude: -16.6869,
          longitude: -49.2648,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'PERF-U-150-60',
          material_description: 'Perfil U Enrijecido 150x60x2,25mm',
          material_group: 'PERFIS',
          quantity: 35.8,
          unit: 't',
          weight_tons: 35.8,
          order_value_brl: 186160,
          order_date: '2026-09-02',
          requested_delivery_date: '2026-09-09',
          planned_delivery_date: '2026-09-09',
          itinerary_code: '030',
          itinerary_description: 'GO / Centro-Oeste Eixo Brasília & Goiânia',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 17.3,
          stock_future_tons: 18.5,
          pcp_schedule_ref: 'WS-L2-2026-W37',
          pcp_production_status: 'Disponibilidade futura (PCP 2d)', // "Existem 18,5 t para GO aguardando produção prevista para os próximos dois dias"
          commercial_priority: 'ALTA',
          customer_restrictions: { veiculo_max: 'Carreta Bitrem' },
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        {
          sales_order: '4500981515',
          sales_order_item: '10',
          customer_code: 'CLI-97025',
          customer_name: 'Distribuidora de Aço Planalto',
          city: 'Brasília',
          uf: 'DF',
          cep: '70000-000',
          latitude: -15.7975,
          longitude: -47.8919,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'PERF-U-100-40',
          material_description: 'Perfil U Simples 100x40x2,00mm',
          material_group: 'PERFIS',
          quantity: 31.2,
          unit: 't',
          weight_tons: 31.2,
          order_value_brl: 162240,
          order_date: '2026-09-03',
          requested_delivery_date: '2026-09-10',
          planned_delivery_date: '2026-09-10',
          itinerary_code: '030',
          itinerary_description: 'GO / Centro-Oeste Eixo Brasília & Goiânia',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 31.2,
          stock_future_tons: 0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'MEDIA',
          customer_restrictions: {},
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        {
          sales_order: '4500981530',
          sales_order_item: '10',
          customer_code: 'CLI-97040',
          customer_name: 'Estruturas Metálicas Anápolis',
          city: 'Anápolis',
          uf: 'GO',
          cep: '75000-000',
          latitude: -16.3267,
          longitude: -48.9534,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'TUB-RED-4-4MM',
          material_description: 'Tubo Redondo 4" x 4,25mm Sch 40',
          material_group: 'TUBOS',
          quantity: 29.0,
          unit: 't',
          weight_tons: 29.0,
          order_value_brl: 153700,
          order_date: '2026-09-04',
          requested_delivery_date: '2026-09-11',
          planned_delivery_date: '2026-09-11',
          itinerary_code: '030',
          itinerary_description: 'GO / Centro-Oeste Eixo Brasília & Goiânia',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 29.0,
          stock_future_tons: 0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'ALTA',
          customer_restrictions: {},
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        // Itinerário 020 - SP / Capital & Vale
        {
          sales_order: '4500981600',
          sales_order_item: '10',
          customer_code: 'CLI-98010',
          customer_name: 'Caldeiraria São Paulo Ltda',
          city: 'Campinas',
          uf: 'SP',
          cep: '13010-000',
          latitude: -22.9056,
          longitude: -47.0608,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'TUB-RED-4-4MM',
          material_description: 'Tubo Redondo 4" x 4,25mm Sch 40',
          material_group: 'TUBOS',
          quantity: 71.0,
          unit: 't',
          weight_tons: 71.0,
          order_value_brl: 376300,
          order_date: '2026-09-01',
          requested_delivery_date: '2026-09-07',
          planned_delivery_date: '2026-09-07',
          itinerary_code: '020',
          itinerary_description: 'SP / Capital & Vale do Paraíba',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 71.0,
          stock_future_tons: 0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'CRITICA',
          customer_restrictions: { veiculo_max: 'Vanderleia' },
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        {
          sales_order: '4500981615',
          sales_order_item: '10',
          customer_code: 'CLI-98025',
          customer_name: 'Paulista Montagens Industriais',
          city: 'São Paulo',
          uf: 'SP',
          cep: '01001-000',
          latitude: -23.5505,
          longitude: -46.6333,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'PERF-U-150-50',
          material_description: 'Perfil U Simples 150x50x3,00mm',
          material_group: 'PERFIS',
          quantity: 58.0,
          unit: 't',
          weight_tons: 58.0,
          order_value_brl: 301600,
          order_date: '2026-09-02',
          requested_delivery_date: '2026-09-09',
          planned_delivery_date: '2026-09-09',
          itinerary_code: '020',
          itinerary_description: 'SP / Capital & Vale do Paraíba',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 45.0,
          stock_future_tons: 13.0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'ALTA',
          customer_restrictions: { restricao_vuc: true },
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        // Itinerário 025 - MG / Sul de Minas (Pouso Alegre, Varginha)
        {
          sales_order: '4500981700',
          sales_order_item: '10',
          customer_code: 'CLI-99010',
          customer_name: 'Siderúrgica Sul de Minas',
          city: 'Pouso Alegre',
          uf: 'MG',
          cep: '37550-000',
          latitude: -22.2303,
          longitude: -45.9366,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'TUB-RET-80-40',
          material_description: 'Tubo Retangular 80x40x2,65mm',
          material_group: 'TUBOS',
          quantity: 68.0,
          unit: 't',
          weight_tons: 68.0,
          order_value_brl: 340000,
          order_date: '2026-09-01',
          requested_delivery_date: '2026-09-07',
          planned_delivery_date: '2026-09-07',
          itinerary_code: '025',
          itinerary_description: 'MG / Sul de Minas & Circuito das Águas',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 68.0,
          stock_future_tons: 0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'ALTA',
          customer_restrictions: {},
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        {
          sales_order: '4500981715',
          sales_order_item: '10',
          customer_code: 'CLI-99030',
          customer_name: 'Varginha Agro Implementos',
          city: 'Varginha',
          uf: 'MG',
          cep: '37000-000',
          latitude: -21.5519,
          longitude: -45.4308,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'BAR-CH-50-6',
          material_description: 'Barra Chata Laminada 2" x 1/4"',
          material_group: 'BARRAS',
          quantity: 34.2,
          unit: 't',
          weight_tons: 34.2,
          order_value_brl: 177840,
          order_date: '2026-09-03',
          requested_delivery_date: '2026-09-08',
          planned_delivery_date: '2026-09-08',
          itinerary_code: '025',
          itinerary_description: 'MG / Sul de Minas & Circuito das Águas',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 34.2,
          stock_future_tons: 0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'MEDIA',
          customer_restrictions: {},
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        // Itinerário 050 - RJ / Sul Fluminense
        {
          sales_order: '4500981800',
          sales_order_item: '10',
          customer_code: 'CLI-99100',
          customer_name: 'Aços Fluminense & Tubos',
          city: 'Volta Redonda',
          uf: 'RJ',
          cep: '27250-000',
          latitude: -22.5232,
          longitude: -44.1042,
          has_valid_geo: true,
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'TUB-RED-2-3MM',
          material_description: 'Tubo Redondo DIN 2440 2" x 3,00mm',
          material_group: 'TUBOS',
          quantity: 47.6,
          unit: 't',
          weight_tons: 47.6,
          order_value_brl: 238000,
          order_date: '2026-09-02',
          requested_delivery_date: '2026-09-09',
          planned_delivery_date: '2026-09-09',
          itinerary_code: '050',
          itinerary_description: 'RJ / Sul Fluminense & Baixada',
          delivery_condition: 'CIF',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 47.6,
          stock_future_tons: 0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'ALTA',
          customer_restrictions: {},
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
        // Caso de Alerta Cadastral: Pedido sem CEP/Geolocalização para testar validação defensiva
        {
          sales_order: '4500981999',
          sales_order_item: '10',
          customer_code: 'CLI-99999',
          customer_name: 'Metalúrgica Alvorada Sem Coordenada',
          city: 'Alfenas',
          uf: 'MG',
          cep: '',
          latitude: 0,
          longitude: 0,
          has_valid_geo: false, // Localização pendente
          company_code: '1000',
          company_name: 'CIAFAL',
          shipping_center_code: '1001',
          shipping_center_name: '1001 - Usina Divinópolis Matriz',
          origin_plant: 'CIAFAL Matriz',
          deposit_code: 'DP04',
          material_code: 'TUB-RED-2-3MM',
          material_description: 'Tubo Redondo DIN 2440 2" x 3,00mm',
          material_group: 'TUBOS',
          quantity: 12.0,
          unit: 't',
          weight_tons: 12.0,
          order_value_brl: 60000,
          order_date: '2026-09-04',
          requested_delivery_date: '2026-09-12',
          planned_delivery_date: '2026-09-12',
          itinerary_code: '025',
          itinerary_description: 'MG / Sul de Minas & Circuito das Águas',
          delivery_condition: 'FOB',
          order_status: 'LIBERADO',
          credit_status: 'APROVADO',
          stock_available_tons: 12.0,
          stock_future_tons: 0,
          pcp_schedule_ref: '',
          pcp_production_status: 'Disponível agora',
          commercial_priority: 'BAIXA',
          customer_restrictions: {},
          assigned_load_id: '',
          rfid_tag_verified: true,
        },
      ]

      for (let i = 0; i < orders.length; i++) {
        const o = orders[i]
        const rec = new Record(orderCol, o)
        app.save(rec)
      }
    }

    // 3. Cadastrar Cargas Planejadas do TMS (tms_planned_loads) para integração bidirecional imediata
    const loadCol = app.findCollectionByNameOrId('tms_planned_loads')
    const loadCount = app.findRecordsByFilter(
      'tms_planned_loads',
      "load_number != ''",
      '-created',
      1,
      0,
    ).length

    if (loadCount === 0) {
      const cargas = [
        {
          load_number: 'CRG-2026-0151',
          status: 'CARGA_PLANEJADA',
          origin_plant: 'CIAFAL Matriz',
          origin_city: 'Divinópolis',
          origin_uf: 'MG',
          itinerary_code: '015',
          itinerary_description: 'MG / Triângulo',
          destinations_sequence: [
            {
              city: 'Divinópolis',
              uf: 'MG',
              client: 'Indústria Mecânica Santos',
              weight_tons: 27.8,
            },
            { city: 'Uberaba', uf: 'MG', client: 'Cerealista & Silos Uberaba', weight_tons: 39.8 },
          ],
          destinations_summary: 'Divinópolis → Uberaba',
          total_weight_tons: 67.6,
          total_orders_count: 2,
          total_customers_count: 2,
          vehicle_type_suggested: 'Bitrem Articulado 9 eixos (74 t)',
          vehicle_capacity_tons: 74.0,
          load_occupancy_pct: 91.3,
          carrier_name: 'Expresso Triângulo Transportes Ltda',
          carrier_code: 'TRAN-0042',
          estimated_freight_cost_brl: 14196,
          estimated_toll_cost_brl: 410,
          estimated_savings_brl: 2840,
          total_unloading_stops: 2,
          total_distance_km: 480,
          estimated_travel_time_hours: 8.5,
          departure_planned_date: '2026-09-08',
          orders_json: [
            {
              sales_order: '4500981310',
              item: '10',
              weight: 27.8,
              client: 'Indústria Mecânica Santos',
              city: 'Divinópolis',
            },
            {
              sales_order: '4500981295',
              item: '10',
              weight: 39.8,
              client: 'Cerealista & Silos Uberaba',
              city: 'Uberaba',
            },
          ],
          ai_rationale:
            'Consolidação de pedidos do mesmo eixo rodoviário com janelas de entrega compatíveis no Triângulo Mineiro.',
          is_future_prediction: false,
          wms_rfid_alert:
            'Verificar disponibilidade física do item 4500981295 (sem movimentação RFID recente).',
          created_by_user_id: '',
          created_by_user_name: 'Planejador Logístico CIAFAL',
        },
        {
          load_number: 'CRG-2026-0201',
          status: 'TRANSPORTE_CRIADO',
          origin_plant: 'CIAFAL Matriz',
          origin_city: 'Divinópolis',
          origin_uf: 'MG',
          itinerary_code: '020',
          itinerary_description: 'SP / Capital & Vale do Paraíba',
          destinations_sequence: [
            { city: 'Campinas', uf: 'SP', client: 'Caldeiraria São Paulo Ltda', weight_tons: 71.0 },
          ],
          destinations_summary: 'Divinópolis → Campinas',
          total_weight_tons: 71.0,
          total_orders_count: 1,
          total_customers_count: 1,
          vehicle_type_suggested: 'Bitrem Carga Pesada 9 eixos',
          vehicle_capacity_tons: 74.0,
          load_occupancy_pct: 95.9,
          carrier_name: 'Paulista Log Transportes Rodoviários',
          carrier_code: 'TRAN-0018',
          estimated_freight_cost_brl: 13845,
          estimated_toll_cost_brl: 480,
          estimated_savings_brl: 1950,
          total_unloading_stops: 1,
          total_distance_km: 520,
          estimated_travel_time_hours: 9.0,
          departure_planned_date: '2026-09-07',
          orders_json: [
            {
              sales_order: '4500981600',
              item: '10',
              weight: 71.0,
              client: 'Caldeiraria São Paulo Ltda',
              city: 'Campinas',
            },
          ],
          ai_rationale:
            'Carga fechada (lotação completa 96% de ocupação) para cliente prioritário em Campinas/SP.',
          is_future_prediction: false,
          wms_rfid_alert: '',
          created_by_user_id: '',
          created_by_user_name: 'Planejador Logístico CIAFAL',
        },
      ]

      for (let i = 0; i < cargas.length; i++) {
        const c = cargas[i]
        const rec = new Record(loadCol, c)
        app.save(rec)
      }
    }
  },
  (app) => {
    // Reversão
  },
)
